---
name: Python build
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install flake8 mypy pytest types-PyYAML types-tqdm
            - name: Install tilekiln
              run: python -m pip install -e .
            - name: Lint with flake8
              run: flake8 tilekiln tests --count
            - name: Static analysis with mypy
              run: mypy tilekiln tests
            - name: Test with pytest (unit tests)
              run: pytest
            - name: Test with pytest (integration tests)
              run: pytest -m integration
